### ISSUE TITLE
Backend Thumbnails not working anymore

### ISSUE THREAD

**Issue by xanily** [FriendsOfShopware/FroshThumbnailProcessor#10]
### PHP Version

7.4

### Shopware Version

5.7.7

### Actual behaviour

Thumbnails are no longer displayed in several places in the backend.

- The thumbnail of the article is not displayed in the image tab of article editing

- Marketing -> Product export - Thumbnails stored in the template are linked incorrectly. If I specify in the template that a thumbnail should be sent, only the link to the store is shown. e.g. {$sArticle.image|image:1} becomes https://example.com/

- We use Pickware and on the pick device also article images are not shown anymore

### Expected behaviour

All thumbnails are shown correctly

### Steps to Reproduce?

Just install, activate and configure the Plugin, to use a thumbnail processor.

**Comment by tinect** [comment]
Hey @AliveShiro,

I'm really sorry about the issue you are experiencing.

Due to lack of time, we are focussing on Shopware 6. That's the reason why the plugins for Shopware 5 are not maintained active.

I'd suggest you:
- Please check your pattern
- Try fixing and create a PR

**Comment by xanily** [comment]
Ah.. nvm was my fault :/ My path was somehow wrong...
Sorry to bother you
