### ISSUE TITLE
Bilder im Medienmanager 

### ISSUE THREAD

**Issue by lederwerkstatt** [FriendsOfShopware/FroshThumbnailProcessor#6]
Hallo, 
ich verwende BunnyCDN mit den hier beschriebenen Einstellungen.
Den ThumbnailProcessor in einer Stage-Umgebung ausprobiert und anschließend bin/console frosh:thumbnails:remove ausgeführt. Das war erfolgreich. Sämtliche Bilder wurden im "neuen Format" angezeigt, auch im Mediamanager. Die Thumbnails (200x200 etc) waren entfernt.

Nach der selben Vorgehensweise werden in der Live-Umgebung die Artikelbilder (auch in den Kategorien) korrekt angezeigt. Jedoch nicht im Medienmanager. Dort werden wenige Bilder dargestellt, ansonsten mit gebrochenem Link. Unter "Thumbnails" werden Links zu den bisherigen Größen (200x200 etc.) angezeigt. Diese führen zur den alten Bildadressen, die jedoch nicht mehr vorhanden sind.

Caches leeren (auch Production) bringt keine Lösung.

Ein neues Stage, wieder erstellt aus der Live-Umgebung, zeigt hingegen _keine_ Probleme mit dem Mediamanger...

Hast Du eventuell eine Idee, wie sich das Problem lösen lässt? Ich bin dankbar für jeden Tipp!

Viele Grüße
Armin
![medienmanager](https://user-images.githubusercontent.com/46915429/88137212-5b6f5f00-cbeb-11ea-9d31-cae01f13805c.JPG)

**Comment by tinect** [comment]
Hallo Armin,

hast du schon die Links geprüft, die dort aufgerufen werden? Vermutlich stimmt dort was nicht.
Benutzt du auch den Storage von Bunny? Wenn ja, sind die Bilder alle transferiert?

Viele Grüße
Sebastian

**Comment by lederwerkstatt** [comment]
Hallo Sebastian,
danke für die rasche Reaktion!

Ja, ich benutze den Bunny Storage. Alle Bilder sind transferiert und werden auch im Shop richtig dargestellt nach dem Muster des Thumbnail-Processors, also "...xyz.jpg?width=400&height=400 2x"

Das Problem liegt beim Medienmanager bzw. der Anzeige dort:
Dort sind die alten Pfade_ mit den Links zu den alten Thumbnails, also  "...xyz_200x200.jpg" eingetragen. Da diese jedoch jetzt (nach Einsatz des ThumbnailProcessors), nicht mehr vorhanden sind, wird ein 404 zurückgegeben.
Was noch funktioniert/korrekt ist, ist der Link zum Medium, also dem Originalbild, und ebenso dessen Downloadlink.

Sorry, wenn ich mich etwas unbeholfen ausgedrückt habe.

Viele Grüße
Armin

**Comment by tinect** [comment]
Hey Armin,

welche SW-Version setzt du ein und welche ist es genau?
Die Caches (Browser und Shop) hattest du geleert?

Puuuuh, sonst gerade keine Idee :-(

Viele Grüße

**Comment by lederwerkstatt** [comment]
Hallo Sebastian,
der Shop ist SW 5.6.7
Ja, die Caches hatte ich geleert.

Das Eigenartige an der Sache ist ja, dass ein Stage (StageWareManager), erzeugt aus der Live-Umgebung, tadellos funktioniert ...

Viele Grüße
Armin

**Comment by sacrofano** [comment]
Hallo,
bei mir habe ich das Problem direkt in engine/Shopware/Controllers/Backend/MediaManager.php in der Methode getMediaThumbnailPaths gelöst 
`$thumbnailDir = $projectDir . 'media' . DIRECTORY_SEPARATOR . strtolower($media['type']) . DIRECTORY_SEPARATOR . 'thumbnail' . DIRECTORY_SEPARATOR;
$path = $thumbnailDir . $this->removeSpecialCharacters($media['name']) . '_' . $size . '.' . $media['extension'];`

ersetzt durch:
`$thumbnailDir = $projectDir . 'media' . DIRECTORY_SEPARATOR . strtolower($media['type']) . DIRECTORY_SEPARATOR;
 $path = $thumbnailDir . $this->removeSpecialCharacters($media['name']) . '.' . $media['extension'];`

Das Problem scheint zu sein, dass die Pfade erst im alten Format zusammengebaut werden und dann der MD5 darauf berechnet wird.
