### ISSUE TITLE
Shopware 5 or 6?

### ISSUE THREAD

**Issue by peterjaap** [FriendsOfShopware/FroshThumbnailProcessor#7]
It is from first glance unclear whether this plugin is for Shopware 5 or Shopware 6. You can add a topic under the Gear icon on the repo homepage;

![image](https://user-images.githubusercontent.com/431360/91977863-8f2dc080-ed23-11ea-9838-72f146ea9379.png)

**Comment by peterjaap** [comment]
Also see https://www.p16r.nl/2020-09-02-shopware-5-vs-shopware-6-plugins/

**Comment by tinect** [comment]
Thank you. I added them into this repo. Others will follow.
