### ISSUE TITLE
Update für Shopware 5.7x

### ISSUE THREAD

**Issue by lederwerkstatt** [FriendsOfShopware/FroshThumbnailProcessor#8]
Die aktuelle Version ist noch nicht kompatibel mit SW 5.7x 

Die Meldung vor Abschluss des Shopware-Updates von 5.6.10 auf 5.7 oder 5.7.1 :

> Slim Application Error
> The application could not run because of the following error:
> 
> Details
> Type: Symfony\Component\DependencyInjection\Exception\InvalidArgumentException
> Message: Top-level services must have "id" attribute, none found in "/var/www/vhosts/xxxx.com/httpdocs/shop/stage/5/custom/plugins/FroshThumbnailProcessor/Resources/services.xml" at line 15.
> File: /var/www/vhosts/xxxx.com/httpdocs/shop/stage/5/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php
> Line: 440

Wird es ein Update geben?

VG Armin

**Comment by tinect** [comment]
Hi @lederwerkstatt,

I'll have a look on it this week and will ping you, if it's updated.

**Comment by tinect** [comment]
Hi @lederwerkstatt,

Could you please check with this change on services.xml? https://github.com/FriendsOfShopware/FroshThumbnailProcessor/commit/3cbce59edfbd468b0e59b3858534fb9f2a3470f4#diff-be2a105993f06a196e5a6dd527521c7f07bac5c6b1392851a1e57981cec7ec09

**Comment by pumpger** [comment]
HelloTinect
with the updated service.xml the problem is fixed and the FroshThumbnailProcessor works fine.

Thanks a lot for the work and the super plugin!

Many greetings
Armin
